# Generated by Django 2.0.1 on 2019-04-22 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='QueAndAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=100, verbose_name='标准问题')),
                ('answer', models.TextField(default='', max_length=300, verbose_name='标准回答')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问答语料',
                'verbose_name_plural': '问答语料',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='标签名称')),
                ('belong', models.ForeignKey(blank=True, help_text='选择上一级类别，不选择为最高类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belong_tag', to='corpus.Tag', verbose_name='上一级标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Tag2Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_classification', to='corpus.QueAndAns', unique=True, verbose_name='标准问题')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Tag', verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '问题标签映射',
                'verbose_name_plural': '问题标签映射',
            },
        ),
        migrations.CreateModel(
            name='Word2Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2tag_tag', to='corpus.Tag', verbose_name='关键词')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2tag_word', to='corpus.KeyWord', verbose_name='关键词')),
            ],
            options={
                'verbose_name': '关键词映射',
                'verbose_name_plural': '关键词映射',
            },
        ),
    ]
