# Generated by Django 2.0.1 on 2019-05-21 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(default='', max_length=300, verbose_name='未知问题')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('state', models.IntegerField(choices=[(0, '未解决'), (1, '已解决'), (2, '无效问题')], default=0, verbose_name='解决状态')),
            ],
            options={
                'verbose_name': '问题收集',
                'verbose_name_plural': '问题收集',
            },
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=50, unique=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, unique=True, verbose_name='标签名称'),
        ),
        migrations.AlterUniqueTogether(
            name='word2tag',
            unique_together={('word', 'tag')},
        ),
    ]
